services:
  api:
    build:
      context: ./backend
    container_name: hexagonal_api
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
