services:
  db:
    image: postgres:15
    container_name: hexagonal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hexagonal
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    container_name: hexagonal_api
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata:
